### PR TITLE
fix #89 - MinGW linker error

### LINKED ISSUE #89: MinGW linker error introduced in #66
I'm getting linker errors with MinGW for multiple definitions of `inet_pton()` and `inet_ntop()` because `netcode.io` exports those since #66. `netcode.io` should not export those.

A quick fix would be to declare those functions introduced in #66 `static` to stop them from leaking into the linker.

The more correct way, as pointed out in #65, would be to check for Windows feature level Vista or higher, and throw an error if not (`#if _WIN32_WINNT < 0x0600`), to ensure the functions are declared.

### PR DESCRIPTION
**Pull request by Green-Sky**
Making sure the Windows feature level is set to Vista or above.

The only question now is how to do the premake.
Is it ok to just define `_WIN32_WINNT` there, in the `if os.istarget "windows" then` section?

```
defines { "_WIN32_WINNT=0x0600" }
```

### CODE REVIEW

**Comment by gafferongames** [comment]
I'm not sure. This approach seems like it may have side effects. is there another way of doing this?

**Comment by nxrighthere** [comment]
If you want to remove implementation instead of hiding it, then
```
add_definitions(-DWINVER=0x0601)
add_definitions(-D_WIN32_WINNT=0x0601)
```
should be added to CMake.

**Comment by gafferongames** [comment]
We use premake5?

**Comment by nxrighthere** [comment]
Ah, yes, I completely forgot that converted it to CMake. 😄

**Comment by Green-Sky** [comment]
> This approach seems like it may have side effects.
Thats why I'm asking.

> ... I converted it to CMake a while ago, locally.
Same here.

Is there no way to tell in premake, if we are building with MinGW?

**Comment by nxrighthere** [comment]
Well, it's okay to use these macros (I'm using them in another networking library). I don't think that someone cares about the support of Windows Server 2003, so...

Not familiar with the premake, sorry, can't help with that.

**Comment by gafferongames** [comment]
Happy to accept a PR from anybody who can test it. I dev on Mac, so I can't. Closing the PR until then. cheers all -- Glenn
